### ISSUE TITLE
Site sends 301 response code on redirect

### ISSUE THREAD

**Issue by lucas-pelton** [Viper007Bond/allow-numeric-stubs#3]
An all-numeric URL may come from part numbers, serial numbers, etc, and probably rely on search engines to index the unmodified numerical slug.

A status response of 301 creates a situation where search engines may update their index to the redirected URL /######-2/ whereas a 302 redirect will not initiate this update. And more specifically 302 has been superceded by 303 and 307 responses, with 307 likely the appropriate one.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_Redirection

I see that you're hooking into wp_unique_post_slug and am not sure you can control the redirect status from where you're doing this modification, so changing to 307 might not be an option.  Thoughts?

**Comment by Viper007Bond** [comment]
Yeah, all of the redirection is being handled natively by WordPress. I believe it's the same functionality that redirects partial URLs to their canonical URLs, for example https://alex.blog/2017/06/25/drones-work-gre

As such, while most likely doable, this is outside the scope of my plugin. :)
